### Problem Statement
__Hello!__

You have been hired by 'CACT'(Census Analysis and Collection Team) to help with your numpy programming skills. Your major work for today involves census record management and data analysis.

In [1]:
# Importing header files
import numpy as np
import warnings

warnings.filterwarnings('ignore')

#New record
new_record=[[50,  9,  4,  1,  0,  0, 40,  0]]

#Reading file
data = np.genfromtxt("file.csv", delimiter=",", skip_header=1)

In [2]:
print("\nData: \n\n", data)

print("\nType of data: \n\n", type(data))


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

Type of data: 

 <class 'numpy.ndarray'>


In [3]:
nr=np.array(new_record)

In [4]:
data.shape


(1000, 8)

In [7]:
census=np.concatenate((data,nr))

In [8]:
census

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

### Step 2: 
__We often associate the potential of a country based on the age distribution of the people residing there. We too want to do a simple analysis of the age distribution__



In [86]:
age=census[0:,0:1]
age

array([[39.],
       [50.],
       [38.],
       ...,
       [40.],
       [39.],
       [50.]])

In [84]:
max_age=age.max()
min_age=age.min()
age_mean=age.mean()
age_std=age.std()
print("maximum age =",max_age)
print("minimum age =",min_age)
print("Average age =",age_mean)
print("standard deviation of age=",age_std)

maximum age = 90.0
minimum age = 17.0
Average age = 38.06293706293706
standard deviation of age= 13.341478176165857


### Step 3:
__The constitution of the country tries it's best to ensure that people of all races are able to live harmoniously. Let's check the country's race distribution to identify the minorities so that the government can help them.__

In [85]:
race_0=census[census[:,2]==0]
race_0

array([[34.,  4.,  0.,  1.,  0.,  0., 45.,  0.],
       [35., 10.,  0.,  0.,  0.,  0., 40.,  0.],
       [60.,  6.,  0.,  0.,  0.,  0., 10.,  0.],
       [51.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [25., 10.,  0.,  0.,  0.,  0., 20.,  0.],
       [20.,  9.,  0.,  1.,  0.,  0., 48.,  0.],
       [23., 10.,  0.,  0.,  0.,  0., 25.,  0.],
       [29.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [27., 12.,  0.,  1.,  0.,  0., 40.,  0.],
       [31., 12.,  0.,  0.,  0.,  0., 40.,  0.]])

In [30]:
race_1=census[census[:,2]==1]
race_1

array([[3.000e+01, 1.300e+01, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 1.000e+00],
       [4.000e+01, 1.100e+01, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 1.000e+00],
       [5.400e+01, 1.000e+01, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        6.000e+01, 1.000e+00],
       [3.000e+01, 9.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 1.573e+03,
        3.500e+01, 0.000e+00],
       [4.900e+01, 1.000e+01, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 1.000e+00],
       [3.300e+01, 1.300e+01, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [4.400e+01, 1.400e+01, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [2.800e+01, 9.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [6.000e+01, 9.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [4.200e+01, 9.000e+00, 1.000e+00, 1.000e+00, 0.0

In [31]:
race_2=census[census[:,2]==2]
race_2

array([[5.300e+01, 7.000e+00, 2.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [2.800e+01, 1.300e+01, 2.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [4.900e+01, 5.000e+00, 2.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        1.600e+01, 0.000e+00],
       [3.700e+01, 1.000e+01, 2.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        8.000e+01, 1.000e+00],
       [3.200e+01, 1.200e+01, 2.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        5.000e+01, 0.000e+00],
       [5.400e+01, 9.000e+00, 2.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        2.000e+01, 0.000e+00],
       [3.500e+01, 5.000e+00, 2.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [2.000e+01, 1.000e+01, 2.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.400e+01, 0.000e+00],
       [2.200e+01, 1.000e+01, 2.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        1.500e+01, 0.000e+00],
       [5.700e+01, 1.300e+01, 2.000e+00, 1.000e+00, 0.0

In [32]:
race_3=census[census[:,2]==3]
race_3

array([[2.500e+01, 1.000e+01, 3.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [3.300e+01, 1.000e+01, 3.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [6.500e+01, 7.000e+00, 3.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        4.000e+01, 0.000e+00],
       [2.800e+01, 4.000e+00, 3.000e+00, 1.000e+00, 0.000e+00, 2.179e+03,
        4.000e+01, 0.000e+00],
       [4.400e+01, 7.000e+00, 3.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        4.600e+01, 0.000e+00],
       [4.000e+01, 1.300e+01, 3.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        5.500e+01, 1.000e+00]])

In [33]:
race_4=census[census[:,2]==4]
race_4

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [34]:
len_0=len(race_0)
len_0

10

In [35]:
len_1=len(race_1)
len_1

27

In [37]:
len_2=len(race_2)
len_2

110

In [38]:
len_3=len(race_3)
len_3

6

In [39]:
len_4=len(race_4)
len_4

848

In [43]:
# from result race_3 is having less peoples
minority_race=3

### Step 4: 
__As per the new govt. policy, all citizens above age 60 should not be made to work more than 25 hours per week. Let us look at the data and see if that policy is followed.__

In [87]:
senior_citizen=census[census[0:,0]>60]
senior_citizen

array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

In [88]:
working_hours_sum=senior_citizen.sum(axis=0)[6]
print("Total working hours of senior citizen are ",working_hours_sum)

Total working hours of senior citizen are  1917.0


In [89]:
senior_citizen_len=len(senior_citizen)
print("number of senior citizen is",senior_citizen_len)

number of senior citizen is 61


In [90]:
avg_working_hours=working_hours_sum/senior_citizen_len
print("average working hours of senior citizen",avg_working_hours)

average working hours of senior citizen 31.42622950819672


__Average working hours for senior citizen is more than 25 hours per week .
Govt. policy is not followed__


### Step 5: 
__Our parents have repeatedly told us that we need to study well in order to get a good(read: higher-paying) job. Let's see whether the higher educated people have better pay in general.__

In [53]:
high=census[census[:,1]>10]
high

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [28., 13.,  2., ...,  0., 40.,  0.],
       ...,
       [45., 14.,  4., ...,  0., 45.,  0.],
       [48., 13.,  4., ...,  0., 58.,  1.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [78]:
low=census[census[:,1]<=10]
low

array([[38.,  9.,  4., ...,  0., 40.,  0.],
       [53.,  7.,  2., ...,  0., 40.,  0.],
       [49.,  5.,  2., ...,  0., 16.,  0.],
       ...,
       [56.,  9.,  4., ...,  0., 55.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [91]:
avg_pay_high=high[:,7].sum()/len(high)
print("average high pay",avg_pay_high)

average high pay 0.42813455657492355


In [92]:
avg_pay_low=low[:,7].sum()/len(low)
print("average low pay:",avg_pay_low)

average low pay: 0.13649851632047477


#### higher educated peoples have better pay in general